object Constant {
    const val ENV_BASE_API_URL = "BASE_SCHEDULE_API"
    const val ENV_HIGH_QUALITY_URL = "HIGH_QUALITY_URL"
    const val ENV_MEDIUM_QUALITY_URL = "MEDIUM_QUALITY_URL"
    const val ENV_STAGE_HIGH_QUALITY_URL = "STAGE_HIGH_QUALITY_URL"
    const val ENV_STAGE_MEDIUM_QUALITY_URL = "STAGE_MEDIUM_QUALITY_URL"

    const val ENV_DATE_COUNT_TO_FETCH_TEAMS = "DATE_COUNT_TO_FETCH_TEAMS"

    const val ENV_POST_IMAGES_DOMAIN = "POST_IMAGE_DOMAIN"

    const val ENV_ADMIN_URL = "ADMIN_URL"
    const val ENV_SECRET_KEY = "SECRET_KEY"
}