name: Post Images Cron Job

on:
  push:
    branches:
      - posts
    paths:
      - 'assets/config/pending-posts.json'

  workflow_dispatch:      # Cho phép chạy thủ công nếu cần

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    outputs:
      has_changes: ${{ steps.check.outputs.has_changes }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Amazon Corretto 18.0.2
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '18'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Kotlin Main
        run: |
          export POST_IMAGE_DOMAIN='${{ secrets.S_POST_IMAGE_DOMAIN }}'
          
          ./gradlew run

      - name: Check and commit if changes
        id: check
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Update output at $(date)"
            git push origin posts
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

  deploy: #ffsdata1
    needs: build-and-run
    if: needs.build-and-run.outputs.has_changes == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: posts

      - name: Deploy to ffsdata6
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FFSDATA6 }}
          channelId: live
          projectId: ffsdata6

      - name: Deploy to ffsdata7
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FFSDATA7 }}
          channelId: live
          projectId: ffsdata7

      - name: Deploy to ffsdata8
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FFSDATA8 }}
          channelId: live
          projectId: ffsdata8

      - name: Deploy to ffsdata9
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FFSDATA9 }}
          channelId: live
          projectId: ffsdata9
